import bg1 from '../assets/images/bg1.webp'
import bg2 from '../assets/images/bg2.webp'
import bg3 from '../assets/images/bg3.webp'
import bg4 from '../assets/images/bg4.webp'
import bg5 from '../assets/images/bg5.webp'
import bg6 from '../assets/images/bg6.webp'
import bg7 from '../assets/images/bg7.webp'
import landingpage from '../assets/images/LandingPage.webp'
import blender from '../assets/logos/blender.svg'
import aftereffects from '../assets/logos/after-effects-logo.svg'
import figma from '../assets/logos/figma-logo.svg'
import photoshop from '../assets/logos/photoshop-logo.svg'
import illustrator from '../assets/logos/illustrator-logo.svg'
import vs from '../assets/logos/vs-logo.svg'
import zbrush from '../assets/logos/zbrush-logo.svg'
import iamlogo from '../assets/logos/IAMLogo.svg'
import selfpotrait from '../assets/images/selfpotrait.png'
import notfound from '../assets/images/notfound.png'
import pearsbw from '../assets/logos/pearsbw.svg'
import sheraspacebw from '../assets/logos/sheraspacebw.svg'
import yyvbw from '../assets/logos/yyventuresbw.svg'
import yyv from '../assets/logos/yyv.svg'
import sheraspace from '../assets/logos/sheraspace.svg'
import pears from '../assets/logos/pears.svg'
const Images={
    bg1,bg2,bg3,bg4,bg5,bg6,bg7,landingpage,blender,figma,aftereffects,zbrush,vs,illustrator,photoshop,iamlogo,selfpotrait,notfound,pearsbw,sheraspacebw,yyvbw,yyv,sheraspace,pears
}
export default Images;